### ISSUE TITLE
not_null failure where error tolerance

### ISSUE THREAD

**Issue by StuartMiddleton** [Snowflake-Labs/dbt_constraints#41]
We have a test as follows:

```
        tests:
          - not_null:
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">1000"
```
The purpose of this test is to ensure a certain data completion tolerance and flag where this tolerance is not being met for the business to take action.

Behaviour for newer versions of dbt_constraints attempts to apply a not_null constraint in this situation and fails because it's not a true not_null in the database sense. There needs to be some means to ignore the implementation of this constraint - automatic or by configuration.
