### ISSUE TITLE
Enhancement: Conditional foreign key test to support data vault

### ISSUE THREAD

**Issue by PeteCorbettWS** [Snowflake-Labs/dbt_constraints#48]
Minor enhancement to accept conditional filtering on the child side of the foreign key test (similar to [dbt_utils.relationships_where](https://github.com/dbt-labs/dbt-utils#relationships_where-source) test

The specific scenario is testing of referential integrity between data vault Hub and Satellite tables where [ghost records](https://medium.com/snowflake/data-vault-mysteries-zero-keys-ghost-records-3be7cb05ee94) are added to Satellite tables on initial creation but never to Hubs. All other surrogate keys present in a Satellite table must also be present in the parent Hub

I appreciate the desire to adhere to "referential constraint" as specified in ANSI SQL 92 however I am keen to 
- get the benefit of applying FKs (Snowflake)
- apply ref integrity tests
- retain ghost records in satellite tables

Two approaches I can see:
### child predicate param (similar to dbt_utils.relationships_where)
```yaml
#SATELLITES
   - name: sat_reliability_engineering_functional_location_eca
     description: SATELLITE of Functional Location - attributes related to ECA data
     tests:
      - dbt_constraints.foreign_key:
          fk_column_names:
            - DV_SK_HUB_FUNCTIONAL_LOCATION
          child_predicate: DV_SK_HUB_FUNCTIONAL_LOCATION != repeat('0', 64)::BINARY
          pk_table_name: ref('hub_functional_location')
          pk_column_names:
            - DV_SK_HUB_FUNCTIONAL_LOCATION
          tags: ["data_test"]
```
### nullif condition
```yaml
  #SATELLITES
   - name: sat_reliability_engineering_functional_location_eca
     description: SATELLITE of Functional Location - attributes related to ECA data
     tests:
      - dbt_constraints.foreign_key:
          fk_column_names:
            - DV_SK_HUB_FUNCTIONAL_LOCATION
          fk_nullif: repeat('0', 64)::BINARY
          pk_table_name: ref('hub_functional_location')
          pk_column_names:
            - DV_SK_HUB_FUNCTIONAL_LOCATION
          tags: ["data_test"]
```
Happy to contribute if agreeable on the request
