### ISSUE TITLE
FK relationship to table already in the database

### ISSUE THREAD

**Issue by MeganBeckett** [Snowflake-Labs/dbt_constraints#51]
hi there

Thanks for this handy package. 

I am very new to DBT and currently using it to add some materialized tables to a database which already has tables in it (generated from another process, not dbt).

I want to use `dbt_constraints` to specify the FK relationships to existing tables in the database. But, these are not created as models with dbt. Is this possible?

At the moment, when I run `dbt test` and just specify the table name, it says it passes in creating the FK constraints, but these do not show up in the database or schema as actually have been generated.

As an example, I have this:

```
tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - forecast_period_startdate
            - period_fk
            - facility_fk
            - product_fk
      - dbt_constraints.primary_key:
          column_name: id
          constraint_name: mt_facility_pred_actual_price_pkey
      - dbt_constraints.foreign_key:
          fk_column_name: period_fk
          pk_table_name: period
          pk_column_name: id
```

So, `period` is a table already in the database and I want to make the materialized table `period_fk` column have a Fk constraint to the id of this column. Is this possible?
